### ISSUE TITLE
UnitAwareScheduler does not support target_interval

### ISSUE THREAD

**Issue by hub-cap** [elastic/rally#1120]
I ran into an issue using a track w/ `target-interval` instead of `target-throughput` and it was bombing out [here](https://github.com/elastic/rally/blob/master/esrally/driver/scheduler.py#L268).

**Comment by danielmitterdorfer** [comment]
The actual issue here is that Rally treats tasks with a `target-interval` set to zero as throttled when a `schedule` is specified as well. We will refine the logic so that a `target-interval` of zero is treated as unthrottled if and only if no schedule or one of the built-in schedules (`deterministic`, `poisson`) is defined. We cannot assume the same for arbitrary scheduler implementations though because it might not always be possible to specify a target throughput (e.g. when the scheduler simulates a daily traffic pattern there is no single appropriate target throughput).
