### ISSUE TITLE
Support ability to generate track config identifier

### ISSUE THREAD

**Issue by gingerwizard** [elastic/rally#1123]
## Problem Overview

There are cases where we need to know if the track configuration has changed across multiple runs. This will allow us to potentially skip track actions which be redundant and thus reducing run time. We have tracks in development, for example, where we generate data for indexing. If we know the configuration has not changed, and the data exists on disk, we can skip this specific action saving considerable time.

The track can be changed by:

- A user changing track parameter values
- The track itself changing i.e. we change the default values of a parameter.

Both should be considered in any track hash to avoid stages being skipped when they should be executed.

### 1. Hash Functions

We implement a `Track.__hash__()` which delivers a deterministic value based on the track values. All classes that potentially influence the hash of a track would also implement a `hash`  function. e.g. `Operation.__hash__()`, with these values considered in the final value.  This would allow custom parameter sources to decide whether values should be considered - this decision may depend on their use of the hash e.g. in the data generation case, values which do not  influence the files generated would not be included.

### 2. Expose track parameter values in the track object

This track object is passed to custom parameter sources. If we include a dict of the track parameters it would need to include both the user supplied values as well as any default settings that the user had not specified. 

@danielmitterdorfer

**Comment by danielmitterdorfer** [comment]
With https://github.com/elastic/rally/pull/1135 we provide the necessary infrastructure that custom track processor can implement approach 2 described above. While the user-supplied values via `--track-params` are not directly supplied, the track author can put all relevant parameters into a new `parameters` block in the track. Also, track processors have access to the complete `Track` instance to extract e.g. properties of corpora in order to calculate a stable track identifier.
