### ISSUE TITLE
Deprecated configure method

### ISSUE THREAD

**Issue by craigedmunds** [elastic/rally#1149]
Hey guys, our AMI build tool which includes rally just started failing unexpectedly:

    amazon-ebs:                [--kill-running-processes]
    amazon-ebs:                {race,list,info,create-track,generate,compare,download,install,start,stop}
    amazon-ebs:                ...
    amazon-ebs: esrally: error: argument subcommand: invalid choice: 'configure' (choose from 'race', 'list', 'info', 'create-track', 'generate', 'compare', 'download', 'install', 'start', 'stop')

We've tracked it down to this change:
https://github.com/elastic/rally/commit/f30214c54799c50581c9485af498ae9a25d15544

Appreciate you're evolving the project, but a change to your cli in an incremental update like this is not cool - at least deprecate it but continue to work :)

**Comment by danielmitterdorfer** [comment]
Sorry for your build tool failure. When we introduced the change we pondered whether to consider it breaking, decided against it and did not anticipate automated usage and thus introduced the change in this release. As the release is already out I don't think this is actionable on our side and thus I'm closing the issue. Thanks for your feedback and please note that we document changes such as this one in our [migration guide](https://esrally.readthedocs.io/en/stable/migrate.html). So that's always a good place to check before when upgrade. :)

**Comment by craigedmunds** [comment]
Thats great, but we pin to the minor version and incremental updates just get picked up automatically.

Your cli is your public interface, so of course changing it is a breaking change!
