### ISSUE TITLE
Simplify custom command line argument validation

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#1249]
Rally is currently using [`argparse.type`](https://docs.python.org/3/library/argparse.html#type) to implement [custom validations](https://github.com/elastic/rally/blob/be6718068aae2e9e65da710c9326ff92e731856a/esrally/rally.py#L38-L65). However, thats cumbersome and [`argparse.action`](https://docs.python.org/3/library/argparse.html#action) is more appropriate so we should switch to that.

**Comment by pquentin** [comment]
I wanted to tackle this and investigated a bit about `type` vs. `action`. It turns out that `action` is the more complicated way to do custom validation. Using `type` is recommended [on StackOverflow](https://stackoverflow.com/questions/14117415/in-python-using-argparse-allow-only-positive-integers/14117567), [on this random blog post](https://me.micahrl.com/blog/python-argparse-custom-actions-types/), and by [Steven Bethard, who authored argparse](https://groups.google.com/g/argparse-users/c/tAC1eH1a29c?pli=1).

Please consider closing this issue: the current custom validators are fine.

**Comment by danielmitterdorfer** [comment]
Thanks for your research on this @pquentin! Given your reasoning above I agree, let's close this issue.
