### ISSUE TITLE
All cars should set the heap size

### ISSUE THREAD

**Issue by jpountz** [elastic/rally#131]
I don't think any cars should use the default heap size. Since we now have bootstrap checks that ensure that the JVM memory is set, all users will be forced to set the heap size in production, and I think our benchmarks should try to replicate production setups?

**Comment by jasontedor** [comment]
Relates elastic/elasticsearch#18311

**Comment by danielmitterdorfer** [comment]
This is by intention so we can benchmark the out-of-the-box performance of Elasticsearch (that's why the car is also called "defaults"). However, with #71, we will - by default - run the load test driver and the benchmark candidate on different machines and as a consequence we will also need to adhere with the settings that bootstrap checks enforce. Hence, I'd be ok with specifying a heap size also for the car "defaults".

**Comment by danielmitterdorfer** [comment]
This should be considered when implementing #195.

**Comment by danielmitterdorfer** [comment]
Although we still have a car named `defaults`, we explicitly set the heap size for all cars now (see https://github.com/elastic/rally-teams/blob/master/cars/defaults.ini#L5) since #195 has been merged to master. Hence closing.
