### ISSUE TITLE
Getting an error when running a race on a 3 node Elastic-Search Cluster

### ISSUE THREAD

**Issue by Kavya-Dandamudi** [elastic/rally#1737]
When trying to run a benchmark on a 3 node elastic cluster, we are getting the below error. 

Version of Rally - 2.8. 0
Version of Elastic Search - 7.17.0
The document count of index - 35,845,521

"
[INFO] Race id is [d5179e91-1c44-44a6-9f57-72bcd08891a2]

[ERROR] Cannot race. Error in task executor
        Cannot download data because no base URL is provided.

Attaching the log file
[error.txt](https://github.com/elastic/rally/files/11777759/error.txt)

"

We tried running the benchmark with the Elastic Search DNS and also with the IP's

esrally race --track=/home/ec2-user/tracks/ES-Cluster --target-hosts=Zentity.DNS.Com:9200 --pipeline=benchmark-only --client-options="basic_auth_user:'user',basic_auth_password:'password'"

esrally race --track=/home/ec2-user/tracks/ES-Cluster --target-hosts=10.149.10.14:9200,10.149.10.248:9200,10.149.11.43:9200 --pipeline=benchmark-only --client-options="basic_auth_user:'user',basic_auth_password:'password'"

**Comment by Kavya-Dandamudi** [comment]
We did not get the same issue when running the benchmark on a single node cluster with document count 3,556,667

**Comment by pquentin** [comment]
Thanks very much for your interest in Rally.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/tag/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

That said, when opening your topic, make sure to include your track definition, your Rally configuration file (.ini file), the full logs and the precise Rally invocation that fails. (It's very surprising to see `--track=/home/ec2-user-tracks/ES-Cluster` because that looks like a track path, not a track name.) 

And for what it's worth, the error is saying that `base-url` is not set in the corpora section: https://esrally.readthedocs.io/en/stable/track.html#corpora. And Rally is using the `7.17` branch of `/home/ec2-user/.rally/benchmarks/tracks/default`, not sure if that's expected.
