### ISSUE TITLE
Failed to run Rally with docker

### ISSUE THREAD

**Issue by bensgith** [elastic/rally#1794]
**Rally version**: elastic/rally:latest

**Invoked command**: docker run elastic/rally list tracks

**Configuration file**: no configuration file

**JVM version**: 17.0.6

**OS version**: WIndows 10

**Description of the problem including expected versus actual behavior**:
It failed to run with docker when I was trying to follow the instructions from https://esrally.readthedocs.io/en/stable/docker.html

**Steps to reproduce**:
 1. open Windows Command Prompt
 2. docker pull elastic/rally
 3. docker run elastic/rally list tracks

**Provide logs (if relevant)**:
```
C:\Users\xxx>docker run elastic/rally list tracks

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[ERROR] Cannot list. Could not load component [elser-ingest-speedtest]

Getting further help:
*********************
* Check the log files in /rally/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/2.3.0/.
* Ask a question on the forum at https://discuss.elastic.co/tags/c/elastic-stack/elasticsearch/rally.
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /rally/.rally/logs.

-------------------------------
[INFO] FAILURE (took 6 seconds)
-------------------------------
```

**Describe the feature**:

**Comment by b-deam** [comment]
Thanks for reporting this @bensgith! 

Unfortunately I tried reproing this on my local workstation (MacOS) using the last release (`elastic/rally:2.9.1`) and didn't have any luck. We just published [a new release of Rally (2.10.0)](https://hub.docker.com/layers/elastic/rally/2.10.0/images/sha256-99ead3affcff9e413597997111407574df61d0e0bb004895c6cf4b5018c82252?context=explore) that may fix this, but I can't say for sure because I don't know why it can't load the track.

If the newest version doesn't work, are you able to give me the the actual digest with `$ docker image ls --digests`, and a copy of the actual log file rally writes to under `~/.rally/logs/rally.log`?  You should be able to get the latter with something like:
```
# powershell
$ docker run -v ${PWD}:/rally/ elastic/rally list tracks

# windows
$ docker run -v %cd%:/rally/ elastic/rally list tracks
```

**Comment by b-deam** [comment]
🤦 - ignore me, I see you're using the 2.3.0 image, that's over +2 years old at this point. Can you please try and run the latest images?

**Comment by bensgith** [comment]
The image was pulled by `docker pull elastic/rally`, which I think it should be the latest one 2.9.1

**Comment by gbanasiak** [comment]
Judging by the following line from your console it was 2.3.0:
```
* Read the documentation at https://esrally.readthedocs.io/en/2.3.0/.
```

You can check your image digest with the command provided earlier, i.e. `docker image ls --digests`. The digests are:
```
2.3.0: sha256:0dd09af744b1ff9e86c80ed7b825284419823e0a0ffcb1e8174c26896d29c7a4
2.10.0 (current latest): sha256:99ead3affcff9e413597997111407574df61d0e0bb004895c6cf4b5018c82252
```

**Comment by gbanasiak** [comment]
`2.3.0` was `latest` 2 years ago, please remove it and download `latest` again, or `2.10.0` explicitly.

**Comment by ebadyano** [comment]
closing, @bensgith please re-open if you still see the error
