### ISSUE TITLE
Formatting for user-tags on rally-results

### ISSUE THREAD

**Issue by evanfreed** [elastic/rally#392]
I noticed that `rally-metrics-*` broke up the key/values of `user-tag`'s defined into `meta.tag_` tags:
<img width="225" alt="screen shot 2018-01-11 at 4 31 45 pm" src="https://user-images.githubusercontent.com/2314084/34850993-af93887a-f6ed-11e7-9cb7-3891779e748c.png">

However, it looks like these are getting squashed back into `user-tag` with `rally-results-*`:
<img width="221" alt="screen shot 2018-01-11 at 4 32 25 pm" src="https://user-images.githubusercontent.com/2314084/34850988-a8d85b1e-f6ed-11e7-941a-f7d4b3d932fd.png">

Is it possible to apply this same formatting there as well?

**Comment by danielmitterdorfer** [comment]
Yes, I agree it would be better to split this up as well in `rally-results-*`. Thanks for bringing this up!

**Comment by danielmitterdorfer** [comment]
With the next release, all entries in the indices `rally-races-*` and `rally-results-*` will have a new property `user-tags` which will contain the provided user tags. Contrary to raw results where we have to prefix the user-provided key with `tag_` (because we put them in the `meta` structure together with other meta-information) there is no need for a prefix here because the user-provided key cannot conflict with any Rally-internal keys.

Example:

User provides `--user-tag="os:Linux,cpu:ARM"`. This will be represented in `rally-races-*` and `rally-results-*` as:

```json
"user-tags": {
    "os": "Linux",
     "cpu": "ARM"
}
```
