### ISSUE TITLE
Support for benchmarking Kibana dashboards

### ISSUE THREAD

**Issue by cdahlqvist** [elastic/rally#530]
In the [rally-eventdata-track](https://github.com/elastic/rally-eventdata-track) I am simulating load that includes indexing as well as querying through a number of Kibana dashboards. When the track was initially created, all Kibana dashboards basically resulted in a large `_msearch` query that was proxied by the server component. Since then more logic has been moved server side and this is no longer the case. A typical dashboard can now result in multiple requests that are processed and transformed on the server.

Setting up and simulating this in a parameter source that directly interfaces with Elasticsearch is complex and tedious. It would be great if Rally could be enhanced so that Kibana dashboards could be simulated through queries via the Kibana APIs. This would make it a lot easier to initially capture, configure and maintain.

**Comment by danielmitterdorfer** [comment]
I think directly integrating this into Rally would be pretty complex because it would mean that we need to mimic what Kibana is doing under the hood (which might be different for every version). 

However, an option could be that we provide some kind of generic proxy server that you can point Kibana to (instead of targeting Elasticsearch directly), which records traffic and helps you turn that into a Rally track. This could be useful for situations in general where you want to capture an interaction with Elasticsearch and turn it into a Rally track.

**Comment by danielmitterdorfer** [comment]
With https://github.com/elastic/rally/pull/1112 it is now possible to execute complex request hierarchies with Rally which addresses the execution aspect of this issue. Users are required to come up with an appropriate request structure though. This aspect is tracked in #262 (although it already focusses on a solution).
