### ISSUE TITLE
Search request_cache set to false by default

### ISSUE THREAD

**Issue by javanna** [elastic/rally#596]
**Rally version** (get with `esrally --version`): 1.0.1

**Description of the problem including expected versus actual behavior**:

I am running benchmarks against master and I see that operation-type search sets `request_cache` set to `false` by default, though the docs say:

> cache (optional): Whether to use the query request cache. By default, Rally will define no value thus the default depends on the benchmark candidate settings and Elasticsearch version.

Based on the above, I would expect rally not to set the value, given that I am not providing it in my operation config, maybe though it is a good idea to disable the cache by default, so
I am not sure whether this is a bug or a docs problem.

**Comment by danielmitterdorfer** [comment]
In my opinion this is a bug because we need to be able to differentiate three different cases:

* `request_cache` will not be set when sending the request to Elasticsearch
* `request_cache` set to `false`
* `request_cache` set to `true`

It is awkward to specify the first case if Rally implicitly sets `request_cache` set to `false`. Therefore, I think we should fix the behavior (although it breaks backwards compatibility). Before we fix this, we should also adapt all our tracks to set this value explicitly so we don't introduce any changes to our benchmarks.

**Comment by danielmitterdorfer** [comment]
I had another look and my initial analysis was wrong. In fact, everything is as I've described it above:

* If `cache` is not specified, Rally won't send any request parameter to Elasticsearch thus adhering to whatever default is defined in the index settings
* If `cache` is set to `false` or `true`, we `request_cache` accordingly and send it to Elasticsearch

Therefore, docs and code are aligned and I don't think we need to do anything here.

**Comment by javanna** [comment]
Maybe something has changed, because when I opened the report, rally was setting the cache to false explicitly although I did not provide that parameter.

**Comment by danielmitterdorfer** [comment]
You're right. I only checked the respective runner in Rally but not the parameter source that is providing it. A network analysis has revealed that this parameter is still sent by default. I'll reopen, fix our tracks and then work on a fix in Rally.
