### ISSUE TITLE
Provide a Rally docker image

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally#607]
In some environments it is troublesome to install all of Rally's dependencies. We should therefore provide a Docker image for Rally during the release process. One aspect that we can also address in a later release are use cases which involve the Rally daemon, like load test drivers that are distributed.

**Comment by jordansissel** [comment]
I'd like to use this as well. While testing Elasticsearch configurations under Kubernetes, I'd like to run Rally in Kubernetes to test Elasticsearch within the same k8s cluster.

As a workaround, I can use the Dockerfile in this repository.

**Comment by dliappis** [comment]
Discussed some requirements today:

## Usage

1. Intended to be used against remote ES clusters with pipeline `benchmark-only`; building and setting up Elasticsearch within the container won't be support and doesn't make sense.
2. There won't be (at least in the early stages) and special handling of environment variables translated to cli arguments for Rally; instead the user will be expected to specify all the necessary argument which the entrypoint will supply to the rally executable.
3. Will try to ensure that `.rally` is a VOLUME so that users don't end up stressing the performance of the unionfs on the load generator.
4. Will support running the generators in clustered mode but won't provide tooling for this, as it falls under the responsibility of orchestrators like k8s.
5. Will try to make this compatible with OpenShift too and [arbitrary UIDs](https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html).

## Release
1. Release process should be possible on macOS too, so will stick to vanilla Dockerfile for now and not use tools like [buildah](https://github.com/containers/buildah) or [podman](https://podman.io/).
2. Will implement as a separate step in the build process, to ensure the latest release is available on PyPi before triggering the Docker build process (which will install Rally with pip).
