### ISSUE TITLE
Add "hits" to a query run report

### ISSUE THREAD

**Issue by synhershko** [elastic/rally#619]
As often times there is high correlation between the total number of results matched by a query and the query latency, it'd be very useful to have a "hits" metric in the summary report for each query summary.

**Comment by danielmitterdorfer** [comment]
I agree that this could be useful but the intention behind the summary report is to provide a high-level summary of key metrics. However, Rally stores this information already in the request metadata if you [configure a dedicated Elasticsearch metrics store](https://esrally.readthedocs.io/en/stable/configuration.html#configuration-options). Here is a shortened example document from our nightly benchmarks:

```json
{
  "name": "service_time",
  "sample-type": "warmup",
  "value": 19.701162353157997,
  "task": "randomized-nested-queries",
  "unit": "ms",
  "meta": {
    "success": true,
    "timed_out": false,
    "took": 17,
    "hits": 8505,
    "hits_relation": "eq"
  }
}
```

In case you're wondering about `hits_relation`: This is due to https://github.com/elastic/elasticsearch/pull/35849 which will be available in Elasticsearch 7.0.0.

**Comment by danielmitterdorfer** [comment]
I'm closing this one for now as per my reasoning above.

**Comment by synhershko** [comment]
Hi @danielmitterdorfer , thanks for your detailed response. Only read through it now.

Would you accept a PR for adding the hits count to the summary report? In several use-cases we just had with customers during the sizing operations, we saw that the correlation between total_hits percentiles has very high influence on the high level metrics and as such is really the very first thing we look at after the metrics themselves.
