### ISSUE TITLE
sysstats.py crashed if no valid brand string in cpuinfo on an eMAG aarch64 system

### ISSUE THREAD

**Issue by cnqpzhang** [elastic/rally#718]
**Rally version** (get with `esrally --version`):
1.1.0

**Invoked command**:
esrally --distribution-version=6.0.0

**Configuration file (located in `~/.rally/rally.ini`))**:
all default
datastore.type = in-memory

**JVM version**:
jdk1.8, the minor version does not matter

**OS version**:
CentOS 7.5

**Description of the problem including expected versus actual behavior**:
It is a very straightforward problem, the [py-cpuinfo](https://github.com/workhorsy/py-cpuinfo) tool cannot get a valid brand string from various system info or utilities on my aarch64 testing system. In theory, sysstats.py should handle this as a "Unknown" cpu model, at least. However, as "brand" is not a valid key in cpuinfo.get_cpu_info(), the test subsequently crashed and quit. A strict check as below has to be done.
 
https://github.com/elastic/rally/blob/4c160c8fbe7382f7db2af1d9c74c176f009029e5/esrally/utils/sysstats.py#L48
```
ci=cpuinfo.get_cpu_info()
return ci["brand"] if (cpuinfo_available and "brand" in ci) else "Unknown"
```
This issue was exposed and the quick fix has been verified fine on an Ampere Computing eMAG aarch64 system.

**Comment by dliappis** [comment]
Thanks for the report and suggestion for the fix.

This needs to be addressed in the docs too, but just to clarify, Rally isn't currently tested or supported in any other architecture apart from x86_64 (see details [here](https://esrally.readthedocs.io/en/stable/install.html?highlight=x86_64#prerequisites)). This is also valid for Elasticsearch [at the moment](https://www.elastic.co/support/matrix#matrix_os), however given the availability of the [benchmark-only pipeline](https://esrally.readthedocs.io/en/stable/pipelines.html#benchmark-only) the load driver(s) can be completely isolated from Elasticsearch and run on x86_64 as I presume that the intention isn't to benchmark the performance of Rally, but rather Elasticsearch, on another architecture.

Given the easy fix, we could tackle this in a PR along with a unit test; let me know if you'd like to work on this yourself though, so that we don't end up duplicating the effort.

**Comment by cnqpzhang** [comment]
Thanks for your quick reply @dliappis . I am not familiar with rally so please handle it in the default way.

BTW and FYI, about my testing on an aarch64 system, with the local workaround I have run rally and Elasticsearch, the result is complete, and the report looks good as well (in-memory mode). A very nice project.

**Comment by dliappis** [comment]
Thank you for the kind words @cnqpzhang . We'll try to get a PR out to be a bit more defensive re: what py-cpuinfo returns.
