### ISSUE TITLE
[Feature Request] `esrallyd start` should not daemonize by default

### ISSUE THREAD

**Issue by iwinux** [elastic/rally#732]
Currently `esrallyd start` daemonizes itself to background, which makes it difficult to run properly in Docker containers.

It would be great to add an CLI argument to opt-in / opt-out this behavior.

**Comment by danielmitterdorfer** [comment]
Thanks for your interest in Rally. Rally is a distributed system and uses an actor system called [Thespian](https://github.com/kquick/Thespian) for internal communication between its components. What happens when you issue `esrallyd start` is that we bootstrap the actor system. During bootstrap, the actor system daemonizes itself and as far as I know this is not customizable. This means we cannot do anything about this at the moment and I hope you don't mind that I'm therefore going to close this issue. However, we will probably move away from this approach which should give us more control over startup behavior (i.e. whether to daemonize or not) so we might be able to address this in the future.

A few things that you can consider:

* For many use cases you don't need to start an actor system. For example, if you spin up the benchmark cluster yourself, there is no need for the actor system. Also, if a single load generator machine can generate the load you need for your benchmark, there is also no need for the actor system.
* Since Rally 1.2.1 [we also ship a Docker image](https://esrally.readthedocs.io/en/stable/docker.html)
