### ISSUE TITLE
[Feature Request] use compressed corpora directly

### ISSUE THREAD

**Issue by iwinux** [elastic/rally#752]
Hi,

For some write-intense benchmarks, I run Rally with documents that are over 100GB in size. During the bulk requests stage, it seems that the client machine (i.e.: the one I run Rally) *cannot load documents fast enough*, because 100~200MB/s from a spinning-disk is the best it can offer 😅.

My current options to work around it:

1. run Rally on multiple machines in distributed mode (a little bit involved)
2. use SSD (but IO-optimized servers are in shortage in my environment)

So the feature request is: would it be possible for Rally to load documents from disk in *compressed* form? AFAIK gzip line-oriented file reading is well supported in Python.

Thanks!

**Comment by danielmitterdorfer** [comment]
Thank you for your interest in Rally and for raising this issue. :)


> [...] cannot load documents fast enough, because 100~200MB/s from a spinning-disk

Each (bulk-indexing) client in Rally will read a portion of the data file that you specify. E.g. if you specify 8 clients with a 8 GB file, then the first client will read from Byte 0 to 1 GB, the second one from 1 GB to 2 GB and so on. Because they do this concurrently this will cause a random access pattern and cause poor performance which may lead to a client-side bottleneck. This is the very reason we are [documenting that Rally requires an SSD on the load generator](https://esrally.readthedocs.io/en/stable/install.html#hardware-requirements).

Based on the disk access pattern that I've described above reading from a compressed file will not help much either. You might need to read less data but the underlying problem (random disk access) persists and supporting random access (with [seek](http://man7.org/linux/man-pages/man2/lseek.2.html) might be [complex](https://github.com/elastic/rally/blob/f918edce8b1ef156069a0e741c045772c1382b1c/esrally/utils/io.py#L343)). Therefore, I hope you don't mind that I close this ticket with the suggestion to use an SSD for the load generator.
