### ISSUE TITLE
How to modify the setting parameters of the index

### ISSUE THREAD

**Issue by pengcongfa** [elastic/rally#756]
esrally: 1.2.1
tracks:geopoint

When I execute the following command：
esrally race --pipeline=benchmark-only --target-hosts=127.0.0.1:9200  --track=geopoint --challenge=append-no-conflicts --user-tag="version:6.3.2-no-plugin" --track-params="number_of_replicas:40,store.type:'encrypt_fs' "

Displayed as follows：
Some of your track parameter(s) "store.type" are not used by this track; perhaps you intend to use  instead.

All track parameters you provided are:
- number_of_replicas
- store.type

All parameters exposed by this track:
- bulk_indexing_clients
- bulk_size
- cluster_health
- conflict_probability
- conflicts
- index_settings
- ingest_percentage
- max_num_segments
- number_of_replicas
- number_of_shards
- on_conflict
- recency
- source_enabled
[ERROR] Cannot race. Error in race control (("Unused track parameters ['store.type'].", None))

In additional,  Modifying the index.json  file does not work
How can I set the properties of the index?

**Comment by dliappis** [comment]
Thank you very much for your interest in Rally.

Firstly, you are targeting Elasticsearch 6.x, which means Rally will use the 6 branch of the rally-tracks repo, where you can see that store-type is not configurable: https://github.com/elastic/rally-tracks/blob/6/geonames/index.json#L2-L6

Since this is a user question, and we'd like to direct these kinds of things to the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests and allow other users to benefit from the discussion in the forum.

As such, I hope you don't mind that I close this.
