### ISSUE TITLE
Add telemetry for Safepoint statistics

### ISSUE THREAD

**Issue by drawlerr** [elastic/rally#917]
JVM Safepoints can cause pauses + jitter in benchmarks and without any telemetry they are difficult to thoroughly investigate.

**Comment by danielmitterdorfer** [comment]
In my opinion we should keep the number of telemetry devices low. At best, this would be an option in the `gc` telemetry device (that should maybe be renamed to `jvm-log` or something similar` and we'd allow to pass logging options there with `--telemetry-params` so only safepoint statistics are gathered (instead of other data as well). However, I think it is sufficient for the time being to specify `--telemetry=gc` to gather the necessary data or am I missing something?

**Comment by danielmitterdorfer** [comment]
As mentioned here, let's keep the number of telemetry devices low thus closing.
