### ISSUE TITLE
[question]About the error ConnectionError(check_hostname requires server_hostname)

### ISSUE THREAD

**Issue by ted222** [elastic/rally#926]
Hello, 
I deployed a elasticsearch cluster by eck( Elastic Cloud on Kubernetes). After that, I  used esrally to run a rally on my cluster which deployed on Kubernetes. The command line was:
 esrally --pipeline=benchmark-only --track-path=/root/rally-tracks/ --target-hosts=10.19.0.139:23413  --client-options="use_ssl:true,verify_certs:true,basic_auth_user:'elastic',basic_auth_password:'xxxxxxxx'

the esrally printed out :
[ERROR] Cannot race. Error in race control (ConnectionError(check_hostname requires server_hostname) caused by: ValueError(check_hostname requires server_hostname))

how to do with the problem? how to use https to connect my es on k8s?

**Comment by dliappis** [comment]
Thanks very much for your interest in Rally.

From a quick view I'd say that using IP addresses for the target host together with TLS verification is your issue here; you should use instead use the valid hostname that corresponds to the public certificate (or just `verify_certs:false` is you want to stick with IP addresses and are certain about the security implications).

However, this appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by ted222** [comment]
Thanks very much! I got it.
I can't visit the forum website because of my awful network. So I came here to ask for help. I'm sorry for this, and thanks a lot for your help.
best regards

**Comment by dliappis** [comment]
@ted222 you are welcome, glad this was of some help.
